version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'https://docs.apexohio.net'
      APP_SECRET: 'This-is-the-secret-key-for-self-hosted-document-management-system'
      DATABASE_URL: 'postgresql://docmost:docmost123@db:5432/docmost'
      REDIS_URL: 'redis://redis:6379'
      NODE_ENV: ${NODE_ENV}
      STORAGE_TYPE: ${STORAGE_TYPE}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_IGNORETLS: ${SMTP_IGNORETLS}

      MAIL_REPLY_TO: ${MAIL_FROM_ADDRESS}
      SMTP_DKIM_ENABLED: 'true'
      SMTP_TLS_CIPHERS: 'TLS_AES_256_GCM_SHA384'
      SMTP_POOL: 'true'
      SMTP_RATE_LIMIT: '5'
    volumes:
      - docmost:/app/data/storage
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: docmost123
      POSTGRES_DB: docmost
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - docmost
    restart: unless-stopped

volumes:
  docmost:
  db:
  redis:
  caddy_data:
  caddy_config:
